### ISSUE TITLE
Feature request: manage monitored deployments by configmap 

### ISSUE THREAD

**Issue by matteovivona** [lnsp/k8s-crash-informer#8]
First of all, I would like to congratulate you on the excellent tool!

Sometimes it is also necessary to "monitor” some applications installed via Helm or Operator that don't allow easily inject annotation. Is it possible to manage these particular deployments via some configuration on configmap?

**Comment by lnsp** [comment]
No, that's not possible right now. My idea would be an additional "target" ConfigMap, which defines a list of monitoring targets

```
apiVersion: v1
data:
  deployments:
    - my-deployment1
    - my-deployment2
  replicaSets:
    - ...
  pods:
    - ...
kind: ConfigMap
metadata:
  name: informer-targets
```

and maybe even support something like glob matching (e.g. `my-deployment.v*`) . Would that solve your problem?
